spring.application.name=hr_app
spring.datasource.url=jdbc:postgresql://dpg-d5vml3t6ubrc73cls65g-a.singapore-postgres.render.com:5432/workbook_52zc
spring.datasource.username=workbook_52zc_user
spring.datasource.password=9UprBu14JbAlIHjmrELsvfZuKGJ5N4zB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
