spring.application.name=hr_app
spring.datasource.url=jdbc:postgresql://dpg-d6ooc44r85hc739jh18g-a.singapore-postgres.render.com:5432/hr_db_yw9e
spring.datasource.username=hr_db_yw9e_user
#postgresql://hr_db_yw9e_user:bI9HiP0UUoYdX9frXYhK8stafSY4yVlp@dpg-d6ooc44r85hc739jh18g-a.singapore-postgres.render.com/hr_db_yw9e
spring.datasource.password=bI9HiP0UUoYdX9frXYhK8stafSY4yVlp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.data.jpa.repository.query=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
