package com.hr.demo.enums;

public enum LeaveType {
    SICK_LEAVE, CASUAL_LEAVE, EARNED_LEAVE, MATERNITY_LEAVE, PATERNITY_LEAVE, 
    COMPENSATORY_OFF, UNPAID_LEAVE, MARRIAGE_LEAVE, BEREAVEMENT_LEAVE, STUDY_LEAVE
}
